server:
  port: 8081

spring:
  application:
    name: producer-server
  boot:
    admin:
      client:
        url: "http://localhost:8000"
        username: root
        password: root
        instance:
          prefer-ip: true
  #指定zipkin server的地址
  zipkin:
    base-url: http://localhost:9411
  sleuth:
  #监控开关
    enabled: true
  #采样率
    sampler:
      percentage: 1.0

eureka:
  instance:
    #instance-id: ${spring.application.name}:${server.port} # 修改显示的微服务名为：服务名:端口
    prefer-ip-address: true                       # 设置微服务调用地址为IP优先（缺省为false）
    lease-renewal-interval-in-seconds: 5          # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 15      # 发呆时间，即服务续约到期时间（缺省为90s）
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true                               # 开启健康检查（依赖spring-boot-starter-actuator）
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS