server:
  port: 8763
spring:
  application:
    name: eureka
  profiles:
    active: peer3

eureka:
  server:
    enable-self-preservation: false           # 关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 5000 # 清理间隔（单位毫秒，默认是60*1000）
     #peer-node-read-timeout-ms: 5000
  instance:
    #health-check-url-path: /actuator/health #2.0后actuator的地址发生了变化
    hostname: peer3
  client:
    # 设置是否从注册中心获取注册信息（缺省true）
    # 因为这是一个单点的EurekaServer，不需要同步其它EurekaServer节点的数据，故设为false
    # fetch-registry: false
    # 设置是否将自己作为客户端注册到注册中心（缺省true）
    # 这里为不需要（查看@EnableEurekaServer注解的源码，会发现它间接用到了@EnableDiscoveryClient）
    register-with-eureka: false
    serviceUrl:
      # 实际测试：若修改尾部的eureka为其它的，比如/myeureka，注册中心启动没问题，但服务端在注册时会失败
      # 报告异常：com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/