server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8769/eureka/
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/
        git:
          #uri: https://github.com/forezp/SpringcloudConfig/
          uri: https://github.com/catlvsuger/springcloud-config/
          searchPaths: respo
          username: catlvsuger
          password: deng123jing
      label: master

